services:
  - type: web
    name: symptom-check-ai
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    numInstances: 1
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: symptom-check-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false 
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: symptom-check-db
    databaseName: symptomcheck
    plan: free
    ipAllowList: [] # Allow all connections from anywhere